"""empty message

Revision ID: fa35c4cd2178
Revises: 23f906067173
Create Date: 2018-08-30 19:17:06.306892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa35c4cd2178'
down_revision = '23f906067173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_name_key', 'course', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('course_name_key', 'course', ['name'])
    # ### end Alembic commands ###
